In [1]:
# Load library
import numpy as np

In [2]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

In [3]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [4]:
# Select third element of vector
vector[2]

np.int64(3)

In [5]:
# Select second row, second column
matrix[1,1]

np.int64(5)

In [6]:
 # Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [7]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [8]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [9]:
# Select the last element
vector[-1]

np.int64(6)

In [10]:
 # Reverse the vector
vector[::-1]

array([6, 5, 4, 3, 2, 1])

In [11]:
 # Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
 # Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])